import { Tajawal, Cairo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/footer/Footer";
import "@/i18n";
import I18nProvider from "@/lib/providers/I18nProvider";


const tajawal = Tajawal({
  variable: "--font-ar",
  subsets: ["arabic"],
  weight: ["300", "400", "500", "700"],
});

const cairo = Cairo({
  variable: "--font-en",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "Dr.Victor",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html
      className={`${tajawal.variable} ${cairo.variable}`}
      suppressHydrationWarning
      lang="en"
    >
      <body>
        <I18nProvider>
          <Navbar />
          {children}
          <Footer />
        </I18nProvider>
      </body>
    </html>
  );
}
